#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#
[project]
name = "2026-Rebuilt"
version = "0.1.0"
description = "2026 Robot Code"
readme="README.md"
requires-python=">= 3.11"
dependencies = [
    "black~=26.3.1",
    "mypy>=1.19.1",
    "phoenix6>=26.1.0",
    "photonlibpy~=2026.1.1",
    "pylint>=4.0.2",
    "robotpy>=2026.2.1",
    "robotpy-apriltag>=2026.2.1",
    "robotpy-cli>=2026.0.1",
    "robotpy-halsim-gui>=2026.2.1",
    "robotpy-pathplannerlib>=2026.1.1",
    "robotpy-pykit>=1.0.4",
    "robotpy-pykit-watch>=1.0.0",
    "wpilib>=2026.2.1",
]

[tool.mypy]
python_version = "3.13"
warn_unused_configs = true
explicit_package_bases = true
mypy_path = "."
ignore_missing_imports = true
warn_unused_ignores = true
warn_no_return = true
